# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-04 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_title', models.CharField(max_length=20, unique=True)),
                ('note_body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shared_with', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=10, unique=True)),
                ('passwd', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='note',
            name='note',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livehealthapp.User'),
        ),
    ]
